<Div class="row" style="margin-top:5px; font-size:18px;">
	<Div class="col-md-10 col-md-push-1">
		<div class="well well-sm text-center">Earn {$ref_percent}% referral bonus! Share your referral URL<br>{$domainname}/?r=ePay username,email or BTC address</div>
	</Div>
</Div>
    
<div class="row" style="margin-bottom:5px;"><center>{$ads_3}</center></div>  
    
<div class="clearfix"></div> 

<font style="text-align:justify !important;">
	Bitcoins is a payment system introduced as open-source software in 2009 by developer Satoshi Nakamoto. The payments in the system are recorded in a public ledger using its own unit of account, which is also called Bitcoins. Payments work peer-to-peer without a central repository or single administrator, which has led the US Treasury to call bitcoin a decentralized virtual currency.Although its status as a currency is disputed, media reports often refer to bitcoin as a cryptocurrency or digital currency.				
	<br><br>
	
	Bitcoins are created as a reward for payment processing work in which users offer their computing power to verify and record payments into the public ledger. Called mining, individuals or companies engage in this activity in exchange for transaction fees and newly created bitcoins. Besides mining, bitcoins can be obtained in exchange for fiat money, products, and services. Users can send and receive bitcoins electronically for an optional transaction fee using wallet software on a personal computer, mobile device, or a web application.
	<br><br>
	Bitcoin as a form of payment for products and services has seen growth, and merchants have an incentive to accept the digital currency because fees are lower than the 2-3% typically imposed by credit card processors.The European Banking Authority has warned that bitcoin lacks consumer protections.Unlike credit cards, any fees are paid by the purchaser not the vendor. Bitcoins can be stolen and chargebacks are impossible. Commercial use of bitcoin is currently small compared to its use by speculators, which has fueled price volatility.
	<br><br>
	A Faucet gaves people free bitcoin. You can win bitcoin at a bitcoin faucet by solving things. To get free bitcoins or win free bitcoins you also can referrel with a multiplier of 0,2 to get free Satoshis for just placing a link. <a href="http://en.wikipedia.org/wiki/Bitcoin" target="_blank">
	<br><br>
	More Information on Bitcoin Wikipedia article</a><br><br>


</font> 
  
<div class="row"><center>{$ads_main_bottom}</center></div> 

<footer class="text-center">
	© Copyright {$year} <a href="{$domainname}">{$title}</a><br>
	Generated by <a href="http://epay.info" target="_blank">ePay.info</a> - 2014-{$year}
</footer>
<br>

	</div>
	<div class="col-md-2 hidden-xs text-center"  style="padding-top:35px;">{$ads_right}</div>
	</div>
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="templates/style/javascript/common.js" type="text/javascript"></script>
</body>
</html>