<br>

<footer class="text-center">Generated by <a href="http://epay.info" target="_blank">ePay.info</a></footer>

<br>

	</div>
	<div class="col-md-2 hidden-xs text-center"  style="padding-top:35px;">{$ads_right}</div>
	</div>
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="templates/style/javascript/common.js" type="text/javascript"></script>
</body>
</html>